language: python

python:
  - "3.5"

sudo: false

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org

install:
  - travis_retry pip install -r dev-requirements.txt

before_script:
  - mongo --version
  - mongod --fork --logpath ./mongo.log
  - sleep 10

script:
  - python setup.py develop
  - flake8 jam && behave --format progress && py.test tests

cache: pip
