version: '2'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.volumes/mongodb:/data/db

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./.volumes/elasticsearch:/data/db
