queryParameters:
  filter[key]:
    displayName: Filter
    description: |
      Apply a filter to the results returned.
      Currently only key value queries are supported.
    type: string
    example: |
      filter[key]=value
      filter[name]=Fredrick
      filter[title]=To Kill A Mocking Bird
