queryParameters:
  page:
    displayName: Page
    description: |
      The page of data to fetch from the server.
      Similiar to offset or skip in other databases.
      Fetches results after `page * page[size]`
    type: integer
    example: page=4
    default: 1
    minimum: 1
  page[size]:
    displayName: Page Size
    description: The number of items to return
    type: integer
    example: page[size]=5
    default: 50
    minimum: 1
    maximum: 100
