displayName: List or create <<resourceType | !pluralize>>
get:
  description: |
    Get a list of all <<resourceType | !pluralize>> that the authenticated user
    has at least READ access to.
  is: [ paginated, filterable ]
  responses:
    200:
      body:
        application/vnd.api+json:
          schema: <<resourceType>>-multiple
post:
  description: |
    Create a new <<resourceType>>.
    If an id, the "primary key", is not provided one will be generated.
  body:
    schema: <<resourceType>>-create
  responses:
    201:
      body:
        application/vnd.api+json:
          schema: <<resourceType>>-single
    409:
      body:
        application/vnd.api+json:
          schema: Errors
          example: !include ../examples/errors/conflict.json
