uriParameters:
  <<resourceType>>_ID:
    type: string
get:
  description: |
    Get this <<resourceType>>'s data.
  responses:
    200:
      body:
        application/vnd.api+json:
          schema: <<resourceType>>-single
put:
  description: |
    **Replace** the <<resourceType>> with the provided data.
  body:
    schema: <<resourceType>>-replace
  responses:
    200:
      body:
        application/vnd.api+json:
          schema: <<resourceType>>-single
patch:
  description: >
    Update the <<resourceType>> with the provided data.
    The provided data will be recursively merged with the existing data.
  body:
    schema: <<resourceType>>-update
  responses:
    200:
      body:
        application/vnd.api+json:
          schema: <<resourceType>>-single

delete:
  description: >
    **Delete** this <<resourceType>>
  responses:
    204:
      description: No body
